# Generated by Django 3.1 on 2020-10-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
    ]
